steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/liquid-fort-453318-q8/k8-program1-artifact-registry/container2:latest',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/liquid-fort-453318-q8/k8-program1-artifact-registry/container2:latest',
      ]

  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials gke-cluster-2 --zone us-central1
        kubectl apply -f pvc.yaml
        kubectl apply -f program2-deployment.yaml
        kubectl apply -f program2-service.yaml

images:
  - 'us-central1-docker.pkg.dev/liquid-fort-453318-q8/k8-program1-artifact-registry/container2:latest'

options:
  logging: CLOUD_LOGGING_ONLY
