apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-central1-docker.pkg.dev/liquid-fort-453318-q8/k8-program1-artifact-registry/container2:latest
          volumeMounts:
            - mountPath: /shail_PV_dir
              name: standard-volume
      volumes:
        - name: standard-volume
          persistentVolumeClaim:
            claimName: standard-rwo-pvc
